name: CI/CD

on:
  push:
    branches: [master]
    path-ignore:
      - '**/README.md'
  pull_request:
    branches: [master]


jobs:

  build_ios:
    name: Build (iOS)
    # needs: [flutter_test]
    runs_on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter pub build ios --release --no-codesign

  build_android:
    name: Build (Android)
    # needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          channel: "stable"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter clean
      - run: flutter pub build apk --release --no-codesign

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v2.1.4
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
