name: book_collector
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  adaptive_theme: ^2.3.0
  bloc: ^8.0.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_auth: ^3.0.2
  firebase_core: ^1.5.0
  flow_builder: ^0.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.0
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.0.7
  meta: ^1.3.0
  very_good_analysis: ^2.4.0

  http: ^0.13.3 
  
dev_dependencies:
  bloc_test: ^9.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.0.17
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/